In [17]:
import torch
from torch.utils.data import Dataset
from torchvision import transforms

In [19]:
class Toy(Dataset):
    
    def __init__(self, length=100, transform=None):
        
        self.x = 2 * torch.ones(length, 2)
        self.y = torch.ones(length, 1)
        self.len = length
        self.transform = transform
        
    def __getitem__(self, index):
        
        sample = self.x[index], self.y[index]
        
        if self.transform:
            sample = self.transform(sample)
            
        return sample
    
    def __len__(self):
        
        return self.len

In [20]:
dataset = Toy()
dataset[0]

(tensor([2., 2.]), tensor([1.]))

In [21]:
for i in range(3):
    
    x,y = dataset[i]
    print(i, 'X:', x, 'Y:', y)

0 X: tensor([2., 2.]) Y: tensor([1.])
1 X: tensor([2., 2.]) Y: tensor([1.])
2 X: tensor([2., 2.]) Y: tensor([1.])


In [29]:
class Operation(object):
    
    def __init__(self, addx=1, muly=1):
        
        self.addx = addx
        self.muly = muly
        
    def __call__(self, sample):
        
        x = sample[0]
        y = sample[1]
        x = x + self.addx
        y = y * self.muly
        sample = x, y
        
        return sample

In [28]:
class Mult(object):
    
    def __init__(self, mul=100):
        
        self.mul = mul
        
    def __call__(self, sample):
        
        x = sample[0]
        y = sample[1]
        x = x * self.mul
        y = y * self.mul
        sample = x, y
        
        return sample     

In [13]:
a = Operation()

In [14]:
x_, y_ = a(dataset[0])

In [15]:
t = Toy(transform = a)

In [23]:
t[0]

(tensor([3., 3.]), tensor([1.]))

In [30]:
data = transforms.Compose([Operation(2, 3), Mult(4)])

In [31]:
d = Toy(transform = data)

In [35]:
d[0]

(tensor([16., 16.]), tensor([12.]))