In [1]:
import torch

In [3]:
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
a.ndimension()

2

In [6]:
a.shape

torch.Size([3, 3])

In [8]:
a.size()

torch.Size([3, 3])

In [12]:
a[0 : 1,2]

tensor([3])

In [11]:
a[1:3, 2]

tensor([6, 9])

In [13]:
X = torch.tensor([[1,2],[3,4]])
Y = torch.tensor([[1,2],[3,4]])
Z = X + Y
Z

tensor([[2, 4],
        [6, 8]])

In [14]:
Z = 2 * Z
Z

tensor([[ 4,  8],
        [12, 16]])

In [15]:
X = torch.tensor([[1,2],[3,4]])
Y = torch.tensor([[1,2],[3,4]])
Z = torch.mm(X,Y)
Z

tensor([[ 7, 10],
        [15, 22]])